import 'package:flutter/material.dart';
import 'language_service.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _localizedValues = {
    // --- English ---
    'en': {
      'app_name': 'FieldAI',
      'app_tagline': 'Intelligence for the field. Even without internet.',
      'good_day': 'Good day,',
      'field_worker': 'Field Worker #104',
      'synced': 'Synced',
      'pending_sync': 'Pending Sync',
      'field_summary': 'Field Operations Summary',
      'diagnoses': 'Diagnoses',
      'observations': 'Observations',
      'tools_diagnostics': 'Field Tools & Diagnostics',
      'analyze_crop': 'Analyze Crop Leaf',
      'analyze_crop_sub': 'Identify leaf diseases & receive instant AI treatment protocols',
      'ask_ai': 'Ask FieldAI (Agronomic RAG)',
      'ask_ai_sub': 'Evidence-based guidance from extension manuals & research',
      'record_obs': 'Record Field Observation',
      'record_obs_sub': 'Save GPS coordinates, crop symptoms & notes offline',
      'recent_activity': 'Recent Field Activity',
      'view_all': 'View all',
      'no_activity': 'No field activity recorded yet. Start by analyzing a crop leaf!',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'test_samples': 'Or Test with Realistic Field Samples:',
      'running_ai': 'Running AI Disease Identification Pipeline...',
      'extracting_markers': 'Extracting foliar lesion geometry & pathogen markers',
      'diagnosis_result': 'Diagnosis Result',
      'crop': 'Crop',
      'identified_condition': 'Identified Condition',
      'ai_confidence': 'AI Confidence',
      'view_protocol': 'View Full Protocol',
      'log_observation': 'Log Observation',
      'target_crop': 'Target Crop',
      'gps_coordinates': 'GPS Field Coordinates',
      'infestation_severity': 'Infestation Severity Level',
      'weather_microclimate': 'Microclimate & Ambient Weather',
      'foliar_symptoms': 'Observed Foliar Symptoms',
      'field_notes': 'Agronomic Field Interventions & Notes',
      'save_sqlite': 'Save Observation to SQLite',
      'saved_local_title': 'Saved to SQLite',
      'saved_local_msg': 'Field observation recorded successfully to on-device database.',
      'return_dashboard': 'Return to Dashboard',
      'my_records': 'My Diagnoses & Observations',
      'all_filter': 'All',
      'diagnoses_filter': 'Diagnoses',
      'observations_filter': 'Observations',
      'close_details': 'Close Details',
      'field_analytics': 'Field Analytics & Risk',
      'outbreak_risk': 'Outbreak Spore Vulnerability',
      'pathogen_prevalence': 'Recorded Pathogen Prevalence',
      'export_json': 'Export Field Observations & Diagnoses (JSON)',
      'system_controls': 'Field System Controls',
      'appearance_theme': 'Appearance Theme',
      'language': 'Application Language',
      'select_language': 'Select Language',
      'offline_mode': 'Field Offline Mode',
      'reload_records': 'Reload Sample Agronomic Records',
      'welcome_title': 'Welcome to FieldAI',
      'welcome_sub': 'Sign in to access offline crop diagnostic tools',
      'email': 'Email Address',
      'password': 'Password',
      'sign_in': 'Sign In / Work Offline',
      'create_account': 'Create Account',
      'guest_mode': 'Continue as Guest (Field Offline)',
      'chat_hint': 'Ask an agricultural question...',
      'search_rag': 'Searching Agricultural Knowledge Base (Offline RAG)...',
      'sources_citations': 'Sources & Extension Manuals:',
      // Disease Names
      'disease_early_blight': 'Early Blight (Alternaria solani)',
      'disease_late_blight': 'Late Blight (Phytophthora infestans)',
      'disease_septoria': 'Septoria Leaf Spot (Septoria lycopersici)',
      'disease_leaf_mold': 'Leaf Mold (Passalora fulva)',
      'disease_healthy': 'Healthy Foliage',
      // Severity
      'sev_mild': 'Mild',
      'sev_moderate': 'Moderate',
      'sev_high': 'High',
      'sev_critical': 'Critical',
      'agronomic_protocol': 'Agronomic AI Protocol',
      'diagnostic_rationale': 'Diagnostic Evidence & Leaf Pathology',
      'conducive_climate': 'Conducive Weather Microclimate',
      'ipm_interventions': 'Integrated Pest Management (IPM) Interventions',
      'ai_disclaimer': 'AI predictions are evidence-based tools designed to assist field scouting.',
      'total_records': 'Total Records',
      'recorded_date': 'Recorded Date',
      'details_field_obs': 'Details & Field Observations',
      'no_records_category': 'No records found in this category.',
      'join_fieldai': 'Join FieldAI Platform',
      'join_fieldai_sub': 'Enable local AI disease detection and synchronized agricultural reporting',
      'full_name': 'Full Name',
      'enter_name_val': 'Please enter your name',
      'enter_email_val': 'Enter a valid email address',
      'enter_password_val': 'Password must be at least 6 characters',
      'organization': 'Organization / Cooperative',
      'role': 'Role',
      'role_field_worker': 'Field Worker / Extension Officer',
      'role_farmer': 'Farmer / Producer',
      'role_researcher': 'Agronomic Researcher',
      'already_have_account': 'Already have an account? ',
      'sign_in_link': 'Sign In',
      'registered_offline_msg': 'Account registered locally in SQLite for offline field use.',
      'field_data_archive': 'Field Data Archive',
      'copy_json': 'Copy JSON',
      'copied_clipboard': 'Field data copied to clipboard',
      'done': 'Done',
      'risk_spore_sub': 'Risk of spore proliferation in region',
      'driving_factors': 'Driving Factors: High relative humidity (84%) combined with persistent 18-24°C microclimate favors Alternaria & Phytophthora spore dispersal.',
      // Field Guide & Sync Manager additions
      'field_guide_title': 'Agronomy Field Guide & Encyclopedia',
      'field_guide_sub': 'Offline crop disease pathology, IPM treatments & guides',
      'search_guide_hint': 'Search crop, disease, symptom, or treatment...',
      'no_guide_results': 'No matching agricultural guide entries found.',
      'view_ipm_protocol': 'View IPM Protocol',
      'sync_manager_title': 'Cloud Sync & Queue Manager',
      'sync_manager_sub': 'Inspect background upload queue & test cloud connection',
      'offline_mode_active': 'Offline Field Mode Active',
      'cloud_sync_ready': 'Cloud Synchronization Ready',
      'records_pending_upload': 'record(s) pending cloud synchronization',
      'server_diagnostics': 'Server Connectivity Diagnostics',
      'ping_server': 'Ping Cloud Server',
      'sync_now_btn': 'Synchronize Pending Records Now',
      'synchronizing_queue': 'Synchronizing with Central Registry...',
      'pending_records_queue': 'Pending Synchronization Queue',
      'no_pending_sync': 'Queue is completely synced!',
      'all_synced_desc': 'All field diagnoses & observations are backed up to SQLite and matched with cloud.',
      // Treatment Plans additions
      'start_treatment_plan': 'Start Actionable Treatment Plan',
      'treatment_plan_btn': 'Treatment & Recovery Plan',
      'treatment_plans_header': 'Treatment & Recovery Plans',
      'treatment_plans_sub': 'Track ongoing field treatment phases & dosage calculations',
      'treatment_plan_title': 'Treatment & Recovery Schedule',
      'dosage_calc_title': 'Field Size & Dosage Calculator',
      'water_volume': 'Water Volume',
      'protectant_powder': 'Fungicide / Protectant',
      'knapsack_tanks': 'Knapsack Tanks',
      'treatment_schedule_phases': 'Multi-Phase Treatment Schedule',
      'completed': 'Completed',
      'save_plan_btn': 'Save Treatment Plan to SQLite',
      'plan_updated_btn': 'Update Treatment Milestones',
      'copy_plan_summary': 'Copy Treatment Instructions',
      'plan_saved_sqlite': 'Treatment plan saved to on-device database.',
      'plan_copied_clipboard': 'Complete treatment schedule copied to clipboard.',
      'no_treatment_plans': 'No active treatment plans recorded yet.',
      'no_treatment_plans_sub': 'Create a treatment plan after diagnosing a crop leaf or start a new plan now.',
      'create_treatment_plan': 'Create New Treatment Plan',
      'plan_deleted': 'Treatment plan removed from local database.',
    },

    // --- Amharic (አማርኛ) ---
    'am': {
      'app_name': 'ፊልድ ኤአይ (FieldAI)',
      'app_tagline': 'የእርሻ ብልህነት። ያለ ኢንተርኔትም ቢሆን።',
      'good_day': 'እንደምን አደሩ / ዋሉ፣',
      'field_worker': 'የመስክ ኤክስቴንሽን ባለሙያ #104',
      'synced': 'ተመሳስሏል',
      'pending_sync': 'ያልተመሳሰለ (በመጠባበቅ ላይ)',
      'field_summary': 'የዕለቱ የመስክ ሥራዎች ማጠቃለያ',
      'diagnoses': 'ምርመራዎች',
      'observations': 'የመስክ ምልከታዎች',
      'tools_diagnostics': 'የመስክ መሣሪያዎችና የሰብል ምርመራ',
      'analyze_crop': 'የሰብል ቅጠልን መርምር',
      'analyze_crop_sub': 'የቅጠል በሽታዎችን ለይተው አፋጣኝ የሕክምና መመሪያዎችን ያግኙ',
      'ask_ai': 'ፊልድ ኤአይን ይጠይቁ (የእርሻ ዕውቀት)',
      'ask_ai_sub': 'በግብርና መመሪያዎችና ምርምር ላይ የተመሠረተ ምክር',
      'record_obs': 'የመስክ ምልከታ መዝግብ',
      'record_obs_sub': 'የጂፒኤስ (GPS) መገኛ፣ ምልክቶችና ማስታወሻዎችን ያለ ኢንተርኔት ያስቀምጡ',
      'recent_activity': 'የቅርብ ጊዜ የመስክ እንቅስቃሴዎች',
      'view_all': 'ሁሉንም እይ',
      'no_activity': 'እስካሁን ምንም እንቅስቃሴ አልተመዘገበም። የሰብል ቅጠልን በመመርመር ይጀምሩ!',
      'camera': 'ካሜራ',
      'gallery': 'ጋለሪ',
      'test_samples': 'ወይም በእውነተኛ የቅጠል ናሙናዎች ይሞክሩ:',
      'running_ai': 'የኤአይ (AI) የሰብል በሽታ መመርመሪያ እየሠራ ነው...',
      'extracting_markers': 'የቅጠል ቁስለትና የበሽታ ምልክቶች እየተተነተኑ ነው',
      'diagnosis_result': 'የምርመራ ውጤት',
      'crop': 'ሰብል',
      'identified_condition': 'የተገኘው የበሽታ ዓይነት',
      'ai_confidence': 'የኤአይ እርግጠኝነት',
      'view_protocol': 'ሙሉ የሕክምና መመሪያን እይ',
      'log_observation': 'በምልከታ መዝገብ አስቀምጥ',
      'target_crop': 'የተመረመረው ሰብል',
      'gps_coordinates': 'የእርሻ ቦታ የጂፒኤስ መገኛ',
      'infestation_severity': 'የበሽታው ጥንካሬ / ስፋት ደረጃ',
      'weather_microclimate': 'የአየር ሁኔታና እርጥበት',
      'foliar_symptoms': 'በቅጠሉ ላይ የታዩ ምልክቶች',
      'field_notes': 'የእርሻ እንክብካቤ ማስታወሻዎች',
      'save_sqlite': 'ምልከታውን በስልኩ ላይ መዝግብ',
      'saved_local_title': 'በስልኩ ላይ ተቀምጧል',
      'saved_local_msg': 'የመስክ ምልከታው በስልኩ ዳታቤዝ ውስጥ በተሳካ ሁኔታ ተቀምጧል።',
      'return_dashboard': 'ወደ ዋናው ገጽ ተመለስ',
      'my_records': 'የእኔ ምርመራዎችና ምልከታዎች',
      'all_filter': 'ሁሉም',
      'diagnoses_filter': 'ምርመራዎች',
      'observations_filter': 'ምልከታዎች',
      'close_details': 'ዝጋ',
      'field_analytics': 'የእርሻ ትንታኔና የበሽታ ስጋት',
      'outbreak_risk': 'የበሽታ መስፋፋት ስጋት ደረጃ',
      'pathogen_prevalence': 'የተመዘገቡ የበሽታ ዓይነቶች ስርጭት',
      'export_json': 'መረጃዎችን ወደ ውጭ ላክ (JSON)',
      'system_controls': 'የስርዓት ቅንብሮች',
      'appearance_theme': 'የገጽታ ቀለም (ቀላል / ጨለማ)',
      'language': 'የመተግበሪያ ቋንቋ',
      'select_language': 'ቋንቋ ይምረጡ',
      'offline_mode': 'ያለ ኢንተርኔት የመስክ ሁኔታ',
      'reload_records': 'የናሙና መረጃዎችን እንደገና ጫን',
      'welcome_title': 'እንኳን ወደ ፊልድ ኤአይ በደህና መጡ',
      'welcome_sub': 'ያለ ኢንተርኔት የሰብል ምርመራ ለማድረግ ይግቡ',
      'email': 'የኢሜይል አድራሻ',
      'password': 'የይለፍ ቃል',
      'sign_in': 'ግባ / ያለ ኢንተርኔት ሥራ',
      'create_account': 'አዲስ አካውንት ክፈት',
      'guest_mode': 'እንደ እንግዳ ቀጥል (ያለ ኢንተርኔት)',
      'chat_hint': 'የግብርና ጥያቄዎን ይጠይቁ...',
      'search_rag': 'በግብርና ዕውቀት ማህደር ውስጥ በመፈለግ ላይ...',
      'sources_citations': 'ዋቢ የግብርና መመሪያዎች:',
      // Disease Names
      'disease_early_blight': 'ቀደምት ብላይት (Early Blight)',
      'disease_late_blight': 'የኋለኛው ብላይት (Late Blight)',
      'disease_septoria': 'የሴፕቶሪያ ቅጠል ነጠብጣብ (Septoria)',
      'disease_leaf_mold': 'የቅጠል ሻጋታ (Leaf Mold)',
      'disease_healthy': 'ጤናማ ቅጠል (Healthy)',
      // Severity
      'sev_mild': 'ቀላል',
      'sev_moderate': 'መካከለኛ',
      'sev_high': 'ከፍተኛ',
      'sev_critical': 'አስቸኳይ / አደገኛ',
      'agronomic_protocol': 'የኤአይ የግብርና ሕክምና መመሪያ',
      'diagnostic_rationale': 'የምርመራ ማስረጃና የቅጠል በሽታ ሁኔታ',
      'conducive_climate': 'ለበሽታው አመቺ የአየር ሁኔታ',
      'ipm_interventions': 'የተቀናጀ የተባይና የበሽታ መከላከያ እርምጃዎች (IPM)',
      'ai_disclaimer': 'የኤአይ ትንበያዎች የመስክ ባለሙያዎችን ለመርዳት የተዘጋጁ ናቸው።',
      'total_records': 'አጠቃላይ መረጃዎች',
      'recorded_date': 'የተመዘገበበት ቀን',
      'details_field_obs': 'ዝርዝር መረጃና የመስክ ምልከታዎች',
      'no_records_category': 'በዚህ ዘርፍ ምንም የተመዘገበ መረጃ አልተገኘም።',
      'join_fieldai': 'ፊልድ ኤአይን ይቀላቀሉ',
      'join_fieldai_sub': 'ያለ ኢንተርኔት የሰብል በሽታ መመርመሪያና ሪፖርት ማድረጊያን ያግኙ',
      'full_name': 'ሙሉ ስም',
      'enter_name_val': 'እባክዎ ሙሉ ስምዎን ያስገቡ',
      'enter_email_val': 'ትክክለኛ የኢሜይል አድራሻ ያስገቡ',
      'enter_password_val': 'የይለፍ ቃል ቢያንስ 6 ፊደላት/ቁጥሮች መሆን አለበት',
      'organization': 'ድርጅት / የገበሬዎች ህብረት ስራ ማህበር',
      'role': 'የስራ ድርሻ',
      'role_field_worker': 'የመስክ ባለሙያ / ኤክስቴንሽን ኦፊሰር',
      'role_farmer': 'አርሶ አደር / አምራች',
      'role_researcher': 'የግብርና ተመራማሪ',
      'already_have_account': 'ቀደም ሲል አካውንት አለዎት? ',
      'sign_in_link': 'ግባ',
      'registered_offline_msg': 'ያለ ኢንተርኔት ለመስራት መረጃው በስልኩ ዳታቤዝ ተመዝግቧል።',
      'field_data_archive': 'የመስክ መረጃዎች ማህደር',
      'copy_json': 'ኮፒ አድርግ (JSON)',
      'copied_clipboard': 'የመስክ መረጃዎች ተገልብጠዋል',
      'done': 'ጨርስ',
      'risk_spore_sub': 'በአካባቢው የበሽታው ስርጭት ስጋት',
      'driving_factors': 'አነሳሽ ምክንያቶች: ከፍተኛ እርጥበት (84%) እና ከ18-24°C ሙቀት ለበሽታው መስፋፋት ምቹ ናቸው።',
      // Field Guide & Sync Manager additions
      'field_guide_title': 'የእርሻ መመሪያና የሰብል በሽታዎች ኢንሳይክሎፒዲያ',
      'field_guide_sub': 'ያለ ኢንተርኔት የሰብል በሽታዎች፣ ምልክቶችና የተፈጥሮ ሕክምናዎች ማህደር',
      'search_guide_hint': 'ሰብል፣ በሽታ፣ ምልክት ወይም ሕክምና ፈልግ...',
      'no_guide_results': 'ምንም የተገኘ የግብርና መመሪያ የለም።',
      'view_ipm_protocol': 'ሙሉ ሕክምናውን እይ',
      'sync_manager_title': 'የክላውድ ማመሳሰያና ወረፋ አስተዳዳሪ',
      'sync_manager_sub': 'ያልተላኩ መረጃዎችን መርምርና የግንኙነት ፍጥነትን ሞክር',
      'offline_mode_active': 'ያለ ኢንተርኔት የመስክ ሁኔታ ነቅቷል',
      'cloud_sync_ready': 'የክላውድ ማመሳሰል ዝግጁ ነው',
      'records_pending_upload': 'ያልተመሳሰሉ የመስክ መረጃዎች አሉ',
      'server_diagnostics': 'የሰርቨር ግንኙነት ምርመራ',
      'ping_server': 'ሰርቨሩን ሞክር',
      'sync_now_btn': 'አሁን ሁሉንም አመሳስል',
      'synchronizing_queue': 'ከማዕከላዊ ዳታቤዝ ጋር በማመሳሰል ላይ...',
      'pending_records_queue': 'በመጠባበቅ ላይ ያሉ መረጃዎች ወረፋ',
      'no_pending_sync': 'ሁሉም መረጃዎች ተመሳስለዋል!',
      'all_synced_desc': 'ሁሉም ምርመራዎችና ምልከታዎች በስልኩ ዳታቤዝ ውስጥ ተቀምጠዋል።',
      // Treatment Plans additions
      'start_treatment_plan': 'የሕክምናና የማገገሚያ እቅድ ጀምር',
      'treatment_plan_btn': 'የሕክምናና የማገገሚያ እቅድ',
      'treatment_plans_header': 'የሰብል ሕክምናና ማገገሚያ እቅዶች',
      'treatment_plans_sub': 'የእርሻ ሕክምና ደረጃዎችንና የመድኃኒት መጠንን ተከታተል',
      'treatment_plan_title': 'የሕክምናና የማገገሚያ የጊዜ ሰሌዳ',
      'dosage_calc_title': 'የእርሻ ስፋትና የመድኃኒት መጠን ማስያ',
      'water_volume': 'የውሃ መጠን',
      'protectant_powder': 'የፈንገስ መድኃኒት ዱቄት',
      'knapsack_tanks': 'የጀርባ ርጭት ማሽን (16L)',
      'treatment_schedule_phases': 'ባለብዙ ደረጃ የሕክምና የጊዜ ሰሌዳ',
      'completed': 'ተጠናቋል',
      'save_plan_btn': 'እቅዱን በስልኩ ላይ መዝግብ (SQLite)',
      'plan_updated_btn': 'የተከናወኑ ደረጃዎችን አድስ',
      'copy_plan_summary': 'የሕክምና መመሪያውን ኮፒ አድርግ',
      'plan_saved_sqlite': 'የሕክምና እቅዱ በስልኩ ዳታቤዝ ውስጥ ተቀምጧል።',
      'plan_copied_clipboard': 'ሙሉ የሕክምና መመሪያው ተገልብጧል።',
      'no_treatment_plans': 'እስካሁን ምንም የተመዘገበ የሕክምና እቅድ የለም።',
      'no_treatment_plans_sub': 'የሰብል ቅጠልን ከመረመሩ በኋላ ወይም አዲስ እቅድ በመፍጠር ይጀምሩ።',
      'create_treatment_plan': 'አዲስ የሕክምና እቅድ ፍጠር',
      'plan_deleted': 'የሕክምና እቅዱ ከስልኩ ዳታቤዝ ተሰርዟል።',
    },

    // --- Tigrinya (ትግርኛ) ---
    'ti': {
      'app_name': 'ፊልድ ኤአይ (FieldAI)',
      'app_tagline': 'ናይ ሕርሻ ብልሒ። ብዘይ ኢንተርኔት እውን።',
      'good_day': 'ደሓን ዶ ሓዲርኩም / ውዒልኩም፣',
      'field_worker': 'ናይ መሮር ሰራሕተኛ #104',
      'synced': 'ተመሳሲሉ',
      'pending_sync': 'ዘይተመሳሰለ (ይጽበ ኣሎ)',
      'field_summary': 'ናይ ሎሚ መሮር ስራሕቲ ሓፈሻዊ ትሕዝቶ',
      'diagnoses': 'ምርመራታት',
      'observations': 'ናይ መሮር ትዕዝብትታት',
      'tools_diagnostics': 'ናይ መሮር መሳርሒታትን ናይ ሰብል ምርመራን',
      'analyze_crop': 'ናይ ሰብሊ ቆጽሊ መርምር',
      'analyze_crop_sub': 'ሕማማት ቆጽሊ ብምልላይ ቅልጡፍ ናይ ሕክምና መምርሒ ርኸብ',
      'ask_ai': 'ንፊልድ ኤአይ ሕተት (ናይ ሕርሻ ፍልጠት)',
      'ask_ai_sub': 'ኣብ ምርምርን መምርሕታትን ሕርሻ ዝተመርኮሰ ምኽሪ',
      'record_obs': 'ናይ መሮር ትዕዝብቲ መዝግብ',
      'record_obs_sub': 'ናይ ጂፒኤስ (GPS) ቦታ፣ ምልክታትን መተሓሳሰብታትን መዝግብ',
      'recent_activity': 'ናይ ቀረባ ግዜ መሮር ንጥፈታት',
      'view_all': 'ኩሉ ርአ',
      'no_activity': 'ክሳብ ሕጂ ዝተመዝገበ ንጥፈት የለን። ቆጽሊ ሰብሊ ብምምርማር ጀምር!',
      'camera': 'ካሜራ',
      'gallery': 'ጋለሪ',
      'test_samples': 'ወይ ድማ ብናይ ሓቂ ናሙናታት ቆጽሊ ፈትን:',
      'running_ai': 'ኤአይ (AI) ናይ ሰብሊ ሕማም ይምርምር ኣሎ...',
      'extracting_markers': 'ናይ ቆጽሊ ምልክታት ሕማም ይትንተን ኣሎ',
      'diagnosis_result': 'ናይ ምርመራ ውጽኢት',
      'crop': 'ሰብሊ',
      'identified_condition': 'ዝተረኽበ ዓይነት ሕማም',
      'ai_confidence': 'ናይ ኤአይ ርግጸኝነት',
      'view_protocol': 'ሙሉእ ናይ ሕክምና መምርሒ ርአ',
      'log_observation': 'ኣብ መዝገብ ትዕዝብቲ ኣእቱ',
      'target_crop': 'ዝተመርመረ ሰብሊ',
      'gps_coordinates': 'ናይ መሮር ጂፒኤስ (GPS) ቦታ',
      'infestation_severity': 'ናይቲ ሕማም ብርታዐ ደረጃ',
      'weather_microclimate': 'ኩነታት ኣየርን ርስሓትን',
      'foliar_symptoms': 'ኣብ ቆጽሊ ዝተራእዩ ምልክታት',
      'field_notes': 'ናይ ሕርሻ ክንክን መተሓሳሰቢታት',
      'save_sqlite': 'ትዕዝብቲ ኣብ ሞባይል መዝግብ',
      'saved_local_title': 'ኣብ ሞባይል ተዓቂቡ',
      'saved_local_msg': 'ናይ መሮር ትዕዝብቲ ኣብ ሞባይል ብትኽክል ተመዝጊቡ ኣሎ።',
      'return_dashboard': 'ናብ ቀንዲ ገጽ ተመለስ',
      'my_records': 'ናተይ ምርመራታትን ትዕዝብትታትን',
      'all_filter': 'ኩሉ',
      'diagnoses_filter': 'ምርመራታት',
      'observations_filter': 'ትዕዝብትታት',
      'close_details': 'ዕጾ',
      'field_analytics': 'ናይ መሮር ትንተናን ስግኣት ሕማምን',
      'outbreak_risk': 'ስግኣት ምዝርጋሕ ሕማም',
      'pathogen_prevalence': 'ዝተመዝገቡ ዓይነታት ሕማም',
      'export_json': 'መረዳእታታት ኣውጽእ (JSON)',
      'system_controls': 'ናይ ሲስተም ምምሕዳር',
      'appearance_theme': 'ናይ ገጽ ሕብሪ (ብርሃን / ጸሊም)',
      'language': 'ናይ ኣፕ ቋንቋ',
      'select_language': 'ቋንቋ ምረጽ',
      'offline_mode': 'ብዘይ ኢንተርኔት ናይ መሮር ኩነታት',
      'reload_records': 'ናይ ናሙና መረዳእታታት ዳግማይ ጫን',
      'welcome_title': 'እንቋዕ ናብ ፊልድ ኤአይ ብደሓን መጻእኩም',
      'welcome_sub': 'ብዘይ ኢንተርኔት ናይ ሰብሊ ምርመራ ንምክያድ እቶ',
      'email': 'ኢመይል ኣድራሻ',
      'password': 'መሕለፊ ቃል (Password)',
      'sign_in': 'እቶ / ብዘይ ኢንተርኔት ስራሕ',
      'create_account': 'ሓዱሽ ኣካውንት ክፈት',
      'guest_mode': 'ከም ጋሻ ቀጽል (ብዘይ ኢንተርኔት)',
      'chat_hint': 'ናይ ሕርሻ ሕቶኹም ሕተቱ...',
      'search_rag': 'ኣብ ናይ ሕርሻ ፍልጠት ማህደር ይድለ ኣሎ...',
      'sources_citations': 'መወከሲ ናይ ሕርሻ መምርሕታት:',
      // Disease Names
      'disease_early_blight': 'ቀዳማይ ብላይት (Early Blight)',
      'disease_late_blight': 'ድሕረ ብላይት (Late Blight)',
      'disease_septoria': 'ናይ ሴፕቶርያ ነጥቢ (Septoria)',
      'disease_leaf_mold': 'ናይ ቆጽሊ ሻምግላ (Leaf Mold)',
      'disease_healthy': 'ጥዑይ ቆጽሊ (Healthy)',
      // Severity
      'sev_mild': 'ቀሊል',
      'sev_moderate': 'ማእከላይ',
      'sev_high': 'ላዕለዋይ',
      'sev_critical': 'ሓደገኛ / ህጹጽ',
      'agronomic_protocol': 'ናይ ኤአይ ሕርሻ ሕክምና መምርሒ',
      'diagnostic_rationale': 'ናይ ምርመራ መረዳእታን ኩነታት ሕማም ቆጽልን',
      'conducive_climate': 'ንሕማም ምቹእ ኩነታት ኣየር',
      'ipm_interventions': 'ዝተዋደደ ምክልኻል ሓሳኹን ሕማማትን (IPM)',
      'ai_disclaimer': 'ናይ ኤአይ ትንበያታት ንናይ መሮር ሰራሕተኛታት ንምሕጋዝ ዝተዳለዉ እዮም።',
      'total_records': 'ሓፈሻዊ መረዳእታታት',
      'recorded_date': 'ዝተመዝገበሉ ዕለት',
      'details_field_obs': 'ዝርዝር ሓበሬታን ናይ መሮር ትዕዝብትታትን',
      'no_records_category': 'ኣብዚ ክፍሊ ዝተረኽበ መረዳእታ የለን።',
      'join_fieldai': 'ናብ ፊልድ ኤአይ ተጸንበሩ',
      'join_fieldai_sub': 'ብዘይ ኢንተርኔት ናይ ሰብሊ ሕማም መመርመሪን ጸብጻብ መቕረብን ተጠቐሙ',
      'full_name': 'ሙሉእ ሽም',
      'enter_name_val': 'በጃኹም ሙሉእ ሽምኩም ኣእትዉ',
      'enter_email_val': 'ትኽክለኛ ኢመይል ኣእትዉ',
      'enter_password_val': 'መሕለፊ ቃል ቢያንስ 6 ፊደላት/ቁጽርታት ክኸውን ኣለዎ',
      'organization': 'ትካል / ሕብረት ስራሕ ማሕበር',
      'role': 'ናይ ስራሕ ግደ',
      'role_field_worker': 'ናይ መሮር ሰራሕተኛ / ኤክስቴንሽን ኦፊሰር',
      'role_farmer': 'ሓረስታይ / ኣፍራዪ',
      'role_researcher': 'ናይ ሕርሻ ተመራማሪ',
      'already_have_account': 'ኣካውንት ኣለኩም ዶ? ',
      'sign_in_link': 'እቶ',
      'registered_offline_msg': 'ብዘይ ኢንተርኔት ንምስራሕ መረዳእታ ኣብ ሞባይል ተመዝጊቡ ኣሎ።',
      'field_data_archive': 'ናይ መሮር መረዳእታታት ማህደር',
      'copy_json': 'ኮፒ ግበር (JSON)',
      'copied_clipboard': 'መረዳእታታት ተቐዲሑ ኣሎ',
      'done': 'ወዲአ',
      'risk_spore_sub': 'ኣብቲ ከባቢ ስግኣት ምዝርጋሕ ሕማም',
      'driving_factors': 'ቀንዲ ምኽንያታት: ላዕለዋይ ርስሓት (84%) ከምኡ\'ውን ካብ 18-24°C ሙቐት ንምዝርጋሕ ሕማም ምቹእ እዩ።',
      // Field Guide & Sync Manager additions
      'field_guide_title': 'ናይ ሕርሻ መምርሕን ናይ ሰብሊ ሕማማት ኢንሳይክሎፒድያን',
      'field_guide_sub': 'ብዘይ ኢንተርኔት ናይ ሰብሊ ሕማማት፣ ምልክታትን ባህላዊ ሕክምናታትን ማህደር',
      'search_guide_hint': 'ሰብሊ፣ ሕማም፣ ምልክት ወይ ሕክምና ድለ...',
      'no_guide_results': 'ዝተረኽበ ናይ ሕርሻ መምርሒ የለን።',
      'view_ipm_protocol': 'ሙሉእ ሕክምና ርአ',
      'sync_manager_title': 'ናይ ክላውድ ምምስሳልን ተርታ ምምሕዳርን',
      'sync_manager_sub': 'ዘይተላእኩ መረዳእታታት መርምርን ናይ መስመር ፍጥነት ፈትን',
      'offline_mode_active': 'ብዘይ ኢንተርኔት ናይ መሮር ኩነታት ነቒሑ ኣሎ',
      'cloud_sync_ready': 'ናይ ክላውድ ምምስሳል ድሉው እዩ',
      'records_pending_upload': 'ዘይተመሰሰሉ ናይ መሮር መረዳእታታት ኣለዉ',
      'server_diagnostics': 'ናይ ሰርቨር ርክብ መርመራ',
      'ping_server': 'ሰርቨር ፈትን',
      'sync_now_btn': 'ሕጂ ኩሉ ኣመሳስል',
      'synchronizing_queue': 'ምስ ማእከላይ ዳታቤዝ ይመሳሰል ኣሎ...',
      'pending_records_queue': 'ይጽበዩ ዘለዉ መረዳእታታት',
      'no_pending_sync': 'ኩሉ መረዳእታ ተመሳሲሉ ኣሎ!',
      'all_synced_desc': 'ኩሎም ምርመራታትን ትዕዝብትታትን ኣብ ሞባይል ተዓቂቦም ኣለዉ።',
      // Treatment Plans additions
      'start_treatment_plan': 'ናይ ሕክምናን ምሕዋይን መደብ ጀምር',
      'treatment_plan_btn': 'ናይ ሕክምናን ምሕዋይን መደብ',
      'treatment_plans_header': 'ናይ ሰብሊ ሕክምናን ምሕዋይን መደባት',
      'treatment_plans_sub': 'ናይ መሮር ሕክምና ደረጃታትን መጠን መድሃኒትን ተኸታተል',
      'treatment_plan_title': 'ናይ ሕክምናን ምሕዋይን መደብ ሰሌዳ',
      'dosage_calc_title': 'ናይ መሮር ስፍሓትን መጠን መድሃኒት መተመኒ',
      'water_volume': 'መጠን ማይ',
      'protectant_powder': 'ናይ ፈንገስ መድሃኒት ዱቄት',
      'knapsack_tanks': 'ናይ ዝባን መርጫ ማሽን (16L)',
      'treatment_schedule_phases': 'ብዙሕ ደረጃታት ዘለዎ ናይ ሕክምና ሰሌዳ',
      'completed': 'ተወዲኡ',
      'save_plan_btn': 'መደብ ኣብ ሞባይል መዝግብ (SQLite)',
      'plan_updated_btn': 'ዝተሰርሑ ደረጃታት ሓድስ',
      'copy_plan_summary': 'ናይ ሕክምና መምርሒ ኮፒ ግበር',
      'plan_saved_sqlite': 'ናይ ሕክምና መደብ ኣብ ሞባይል ተመዝጊቡ ኣሎ።',
      'plan_copied_clipboard': 'ሙሉእ ናይ ሕክምና መምርሒ ተቐዲሑ ኣሎ።',
      'no_treatment_plans': 'ክሳብ ሕጂ ዝተመዝገበ ናይ ሕክምና መደብ የለን።',
      'no_treatment_plans_sub': 'ናይ ሰብሊ ቆጽሊ ምስ መረመርኩም ወይ ሓዱሽ መደብ ብምፍጣር ጀምሩ።',
      'create_treatment_plan': 'ሓዱሽ ናይ ሕክምና መደብ ፍጠር',
      'plan_deleted': 'ናይ ሕክምና መደብ ካብ ሞባይል ተሰሪዙ ኣሎ።',
    },

    // --- Afaan Oromoo (Oromiffa) ---
    'om': {
      'app_name': 'FieldAI',
      'app_tagline': 'Ogeessummaa Qonnaa Bakkee. Interneetii maleeyyuu.',
      'good_day': 'Akkam bultan / ooltan,',
      'field_worker': 'Hojjetaa Qonnaa #104',
      'synced': 'Walsimsiifameera',
      'pending_sync': 'Kan eegaa jiru',
      'field_summary': 'Cuunfaa Hojii Qonnaa Har\'aa',
      'diagnoses': 'Qorannoowwan',
      'observations': 'Hubannoowwan Dirree',
      'tools_diagnostics': 'Meeshaalee Dirree fi Qorannoo Biqilaa',
      'analyze_crop': 'Baala Biqilaa Qoradhu',
      'analyze_crop_sub': 'Dhibee baalaa adda baasii qoricha fi qajeelfama AI argadhu',
      'ask_ai': 'FieldAI Gaafadhu (Beekumsa Qonnaa)',
      'ask_ai_sub': 'Qajeelfama qorannoo qonnaa irratti hundaa\'e',
      'record_obs': 'Hubannoo Dirree Galmeessi',
      'record_obs_sub': 'Bakka GPS, mallattoolee fi yaada interneetii malee olkaawwadhu',
      'recent_activity': 'Sochiiwwan Dirree Dhihoo',
      'view_all': 'Hunda ilaali',
      'no_activity': 'Hojiin galmaa\'e hin jiru. Baala biqilaa qorachuun eegali!',
      'camera': 'Kaameraa',
      'gallery': 'Gaalerii',
      'test_samples': 'Yookiin Saamuda Baalaatiin Yaali:',
      'running_ai': 'AI\'n dhibee biqilaa qorachaa jira...',
      'extracting_markers': 'Mallattoolee fi gosa dhibee xiinxalaa jira',
      'diagnosis_result': 'Bu\'aa Qorannoo',
      'crop': 'Biqilaa',
      'identified_condition': 'Gosa Dhibee Argame',
      'ai_confidence': 'Abdatamummaa AI',
      'view_protocol': 'Qajeelfama Yaalaa Guutuu Ilaali',
      'log_observation': 'Galmee Hubannootti Olkaawwadhu',
      'target_crop': 'Gosa Biqilaa',
      'gps_coordinates': 'Teessoo Bakkaa (GPS)',
      'infestation_severity': 'Sadarkaa Hamaa Dhibee',
      'weather_microclimate': 'Haala Qilleensaa fi Jiidha',
      'foliar_symptoms': 'Mallattoolee Baala Irratti Mul\'atan',
      'field_notes': 'Yaadannoowwan Kunuunsa Dirree',
      'save_sqlite': 'Hubannoo Moobaayila Irratti Galmeessi',
      'saved_local_title': 'Moobaayila Irratti Olkaawwameera',
      'saved_local_msg': 'Hubannoon dirree kuusaa deetaa moobaayilaa keessatti galmaa\'eera.',
      'return_dashboard': 'Gara Fuula Duraatti Deebi\'i',
      'my_records': 'Qorannoowwan fi Hubannoowwan Koo',
      'all_filter': 'Hunda',
      'diagnoses_filter': 'Qorannoowwan',
      'observations_filter': 'Hubannoowwan',
      'close_details': 'Cufi',
      'field_analytics': 'Xiinxala Qonnaa fi Sodaa Dhibee',
      'outbreak_risk': 'Sadarkaa Sodaa Babal\'ina Dhibee',
      'pathogen_prevalence': 'Raabsa Dhibeewwan Galmaa\'anii',
      'export_json': 'Deetaa Baasi (JSON)',
      'system_controls': 'Qindaa\'inoota Sirnaa',
      'appearance_theme': 'Bifa Fuulaa (Ifaa / Dukkana)',
      'language': 'Afaan Appilikeeshinii',
      'select_language': 'Afaan Filadhu',
      'offline_mode': 'Haala Dirree (Interneetii Malee)',
      'reload_records': 'Deetaa Saamudaa Haaromsi',
      'welcome_title': 'Baga Gara FieldAItti Dhuftan',
      'welcome_sub': 'Qorannoo biqilaa interneetii malee fayyadamuuf seenaa',
      'email': 'Teessoo Imeelii',
      'password': 'Jecha Iccitii (Password)',
      'sign_in': 'Seeni / Interneetii Malee Hojjadhu',
      'create_account': 'Akkaawuntii Haaraa Bani',
      'guest_mode': 'Akka Keessummaatti Itti Fufi',
      'chat_hint': 'Gaaffii qonnaa qabdan barreessaa...',
      'search_rag': 'Kuusaa beekumsa qonnaa keessaa barbaadaa jira...',
      'sources_citations': 'Madda Qajeelfamoota Qonnaa:',
      // Disease Names
      'disease_early_blight': 'Dhibee Blight Yeroo Duraa (Early Blight)',
      'disease_late_blight': 'Dhibee Blight Boodaa (Late Blight)',
      'disease_septoria': 'Mallattoo Baala Septoria',
      'disease_leaf_mold': 'Dhibee Mooltii Baalaa (Leaf Mold)',
      'disease_healthy': 'Baala Fayyaa (Healthy)',
      // Severity
      'sev_mild': 'Salphaa',
      'sev_moderate': 'Giddu-galeessa',
      'sev_high': 'Ol\'aanaa',
      'sev_critical': 'Hamaa / Ariifachiisaa',
      'agronomic_protocol': 'Qajeelfama Yaala AI Qonnaa',
      'diagnostic_rationale': 'Ragaa Qorannoo fi Haala Dhibee Baalaa',
      'conducive_climate': 'Haala Qilleensa Dhibeef Mijataa',
      'ipm_interventions': 'Tarkaanfiiwwan To\'annoo Dhibee fi Handooqaa (IPM)',
      'ai_disclaimer': 'Tilmaamni AI hojjettoota dirree gargaaruuf kan qophaa\'edha.',
      'total_records': 'Waliigala Deetaa',
      'recorded_date': 'Guyyaa Galmaa\'e',
      'details_field_obs': 'Bal\'ina fi Hubannoowwan Dirree',
      'no_records_category': 'Kutaa kana keessatti deetaan hin argamne.',
      'join_fieldai': 'FieldAItti Dabalamu',
      'join_fieldai_sub': 'Qorannoo dhibee biqilaa interneetii malee fi gabaasa qonnaa walsimsiisuuf',
      'full_name': 'Maqaa Guutuu',
      'enter_name_val': 'Maaloo maqaa keessan galchaa',
      'enter_email_val': 'Imeelii sirrii ta\'e galchaa',
      'enter_password_val': 'Jechi iccitii yoo xiqqaate qubee 6 ta\'uu qaba',
      'organization': 'Dhaabbata / Waldaa Hojii Gamtaa',
      'role': 'Gahee Hojii',
      'role_field_worker': 'Hojjetaa Qonnaa / Ogeessa Dirree',
      'role_farmer': 'Qotee Bulaa / Oomishaa',
      'role_researcher': 'Qorataa Qonnaa',
      'already_have_account': 'Duraan akkaawuntii qabduu? ',
      'sign_in_link': 'Seeni',
      'registered_offline_msg': 'Interneetii malee fayyadamuuf akkaawuntiin kuusaa deetaa keessatti galmaa\'eera.',
      'field_data_archive': 'Kuusaa Deetaa Dirree',
      'copy_json': 'Koppii Godhi (JSON)',
      'copied_clipboard': 'Deetaan dirree koppii ta\'eera',
      'done': 'Xumurame',
      'risk_spore_sub': 'Sodaa babal\'ina dhibee naannichaa',
      'driving_factors': 'Sababoota gurguddoo: Jiidhina qilleensaa ol\'aanaa (84%) fi ho\'a 18-24°C dhibichaaf mijaataadha.',
      // Field Guide & Sync Manager additions
      'field_guide_title': 'Qajeelfama Qonnaa fi Insaayikilooppiidiyaa Dhibee Biqilaa',
      'field_guide_sub': 'Kuusaa dhibee biqilaa, mallattoolee fi yaala uumamaa interneetii malee',
      'search_guide_hint': 'Biqilaa, dhibee, mallattoo ykn yaala barbaadaa...',
      'no_guide_results': 'Qajeelfamni qonnaa walsimu hin argamne.',
      'view_ipm_protocol': 'Yaala Guutuu Ilaali',
      'sync_manager_title': 'Bulchaa Walsimsiisa fi Tarree Cloud',
      'sync_manager_sub': 'Deetaa hin ergamne qoradhuu fi saffisa qunnamtii yaali',
      'offline_mode_active': 'Haalli Dirree Interneetii Malee Hojjechaa Jira',
      'cloud_sync_ready': 'Walsimsiisni Cloud Qophiidha',
      'records_pending_upload': 'deetaa dirree kan hin walsimsiifamne',
      'server_diagnostics': 'Qorannoo Qunnamtii Sarvarii',
      'ping_server': 'Sarvarii Yaali',
      'sync_now_btn': 'Amma Hunda Walsimsiisi',
      'synchronizing_queue': 'Kuusaa giddu-galeessaa wajjin walsimsiisaa jira...',
      'pending_records_queue': 'Tarree Deetaa Eegaa Jiru',
      'no_pending_sync': 'Deetaan hundi walsimsiifameera!',
      'all_synced_desc': 'Qorannoon fi hubannoon hundi kuusaa deetaa moobaayilaa keessatti olkaawwameera.',
      // Treatment Plans additions
      'start_treatment_plan': 'Karoora Yaalaa fi Fayyinaa Eegali',
      'treatment_plan_btn': 'Karoora Yaalaa fi Fayyinaa',
      'treatment_plans_header': 'Karoorawwan Yaala Biqilaa',
      'treatment_plans_sub': 'Sadarkaa yaala dirree fi hamma qorichaa hordofi',
      'treatment_plan_title': 'Sagantaa Yaala fi Fayyina Biqilaa',
      'dosage_calc_title': 'Bal\'ina Dirree fi Shallaggii Qorichaa',
      'water_volume': 'Hamma Bishaanii',
      'protectant_powder': 'Dawaa Farra Fangasii',
      'knapsack_tanks': 'Taankii Baattuu Dugdaa (16L)',
      'treatment_schedule_phases': 'Sagantaa Yaala Sadarkaa Baay\'ee',
      'completed': 'Xumurameera',
      'save_plan_btn': 'Karoora Moobaayila Irratti Galmeessi (SQLite)',
      'plan_updated_btn': 'Sadarkaa Yaalaa Haaromsi',
      'copy_plan_summary': 'Qajeelfama Yaalaa Koppii Godhi',
      'plan_saved_sqlite': 'Karoorri yaalaa kuusaa deetaa moobaayilaa keessatti galmaa\'eera.',
      'plan_copied_clipboard': 'Qajeelfamni yaalaa guutuun koppii ta\'eera.',
      'no_treatment_plans': 'Karoorri yaalaa amma hojjetamaa jiru hin jiru.',
      'no_treatment_plans_sub': 'Baala biqilaa qorachuun booda ykn karoora haaraa uumuun eegalaa.',
      'create_treatment_plan': 'Karoora Yaala Haaraa Uumi',
      'plan_deleted': 'Karoorri yaalaa kuusaa deetaa keessaa haqameera.',
    },
  };

  static String get(String key, [BuildContext? context]) {
    String langCode = LanguageService.instance.languageCode;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

// Easy extension helper on BuildContext
extension AppLocalizationContextExtension on BuildContext {
  String tr(String key) => AppStrings.get(key, this);
}
